== 2 Hello, Haskell!
=== 2.5 Functions
==== Exercises: Comprehension Check

[source]
----
let half x = x / 2

let square x = x * x
----

[source]
----
dpi x = 3.14 * x * x
----

[source]
----
dpi x = pi * x * x
----

=== 2.6 Infix Operators
==== Associativity and precedence
Higher precedence is applied first. Scale is 0-9.
[source]
----
Prelude> :info (^)
(^) :: (Num a, Integral b) => a -> b -> a   -- Defined in ‘GHC.Real’
infixr 8 ^
----

Left associative
[source]
----
2 * 3 * 4
-- is evaluated as if it was
(2 * 3) * 4
----

Right associative
[source]
----
Prelude> 2 ^ 3 ^ 4
2417851639229258349412352
Prelude> 2 ^ (3 ^ 4)
2417851639229258349412352
Prelude> (2 ^ 3) ^ 4
4096
----

==== Exercises: Parentheses and Association

. Different, because `(*)` has a higher precedence than `(+)` (7 vs. 6)
+
[source]
----
8 + 7 * 9 = 71
(8 + 7) * 9 = 135
----

. The same, based on the same precedence comparison as 1
+
[source]
----
perimeter x y = (x * 2) + (y * 2)
perimeter x y = x * 2 + y * 2
----

. Different, because `(/)` has a higher precedence than `(+)` (7 vs. 6)
+
[source]
----
f x = x / 2 + 9
f x = x / (2 + 9)
----

=== 2.7 Declaring values
==== Exercises: Heal the Sick

. Erroneous space after 3
+
[source]
----
let area x = 3. 14 * (x * x)
-- fix
let area x = 3.14 * (x * x)
----

. `b` not defined in scope of `double`
+
[source]
----
let double x = b * 2
-- fix
let double x = x * 2
----

. Improper alignment, top-level expressions should be defined on the same level of indentation
+
[source]
----
include::ch02_2.6_1.hs[]

Prelude> :l ch02_2.6_1.hs
[1 of 1] Compiling Main             ( ch02_2.6_1.hs, interpreted )

ch02_2.6_1.hs:2:4: parse error on input ‘=’
Failed, modules loaded: none.

-- fixed
x = 7
y = 10
f = x + y
----

=== 2.12 Let and where
==== Exercises: A Head Code

[source]
----
let x = 5 in x
-- 5
let x = 5 in x * x
-- 25
let x = 5; y = 6 in x * y
-- 30
let x = 3; y = 1000 in x + 3
-- 6
----

`*let*` rewritten to `*where*`
[source]
----
f1 = x
    where x = 5

f2 = x * x
    where x = 5
    
f3 = x * y
    where x = 5
          y = 6

f4 = x + 3
   where x = 3
         y = 1000
----

==== let rewritten to where for new expressions

[source]
----
include::ch02_2.12_1.hs[]
----

=== 2.13 Chapter Exercises
==== Parenthesization

(Ignoring single-element and whole-element parenthesization)

[source]
----
2 + 2 * 3 - 1
2 + (2 * 3) - 1
(2 + (2 * 3)) - 1
----

[source]
----
(^) 10 $ 1 + 1
(^) 10 $ (1 + 1)
----

[source]
----
2 ^ 2 * 4 ^ 5 + 1
(2 ^ 2) * 4 ^ 5 + 1
(2 ^ 2) * (4 ^ 5) + 1
((2^2) * (4 ^ 5)) + 1
----

==== Equivalent Expressions
. Equivalent
. Equivalent (`10 ^ 2 = 100`, `10 + 9 * 10 == 10 + (9 * 10) == 10 + 90 = 100`)
. Non-equivalent (`400 - 37 = 363`, `(-) 37 400 == 37 - 400 = 363`)
. Non-equivalent (`div 100 3 = 33`, `100/3 == 33.33..`)
. Non-equivalent (`2 * 5 + 18 == (2 * 5) + 18 == 10 + 18 = 28`, `2 * (5 + 8) = 2 * 23 = 46`)

==== More fun with functions

[source]
----
z = 7
x = y ^ 2
waxOn = x * 5
y = z + 8
----
to REPL
[source]
----
let z = 7
let y = z + 8
let x = y ^ 2
let waxOn = x * 5
----
`waxOn == 1125`

. `*waxOn*` results
+
[source]
----
10 + waxOn
-- 1135
(+10) waxOn
-- 1135
(-) 15 waxOn
-- -1110
(-) waxOn 15
-- 1110
----
. `*triple*`
+
[source]
----
let triple x = x * 3
triple waxOn
-- 3375
----
. where waxOn
+
[source]
----
include::ch02_2.12_2.hs[]
----
. rest
+
[source]
----
include::ch02_2.12_3.hs[]
----
+
`*waxOff*` is `*triple*` +
`*waxOff waxOn*` is `*triple waxOn*`
